### PR TITLE
Fixes the build failing due to -Werror because gcc 10+ emits an incorrect "-Werror=return-local-addr"

### PR DESCRIPTION
**Pull request by Morilli**
built for me

### CODE REVIEW

**Comment by YoshiRulz** [comment]
Can confirm this fixes TASEmulators/BizHawk#2865 on Manjaro.

**Comment by nattthebear** [comment]
Isn't the waterbox still on GCC9?  If so, then this is eventually useful but not immediately relevant.

**Comment by YoshiRulz** [comment]
If so that's not enforced in any way or mentioned in the [readme](https://github.com/TASEmulators/BizHawk/tree/master/waterbox#readme):
> We are not prescribing versions for build environment tools (gcc, etc.) [...]

**Comment by CasualPokePlayer** [comment]
GCC 11-12 also are bugged according to Morilli. GCC 9 is only "enforced" due to that being the maximum Ubuntu 20.04 has (without doing some extra work). Ubuntu's latest LTS is also 22.04 now, which at some point we may want to go put in the readme.

**Comment by nattthebear** [comment]
Not prescribing versions isn't the same as supporting all versions.  I have no problem merging this because as just a warning `#pragma` it isn't likely to break anything.  I agree that the entire toolsuite needs to be upgraded, which I'll do when I get a chance.

**Pull request merged**
